### ISSUE TITLE
Firefox Testing  

### ISSUE THREAD

**Issue by paisley-laurenzio** [kayleemenard/kayleemenard#4]
Only comment is that the footer nav is not fixed to the bottom of the screen which you might want it to be for medium size screens. I think this might just be because there is not enough continent to push it down.

![screen shot 2015-10-08 at 8 49 13 am](https://cloud.githubusercontent.com/assets/6371044/10366599/7986cc86-6d99-11e5-89f5-a173164c0457.png)

**Comment by kayleemenard** [comment]
Turns out I forgot to put "overflow:hidden;" in my medium size media query. Thanks!
