### ISSUE TITLE
Microsoft Edge - scroll-down button

### ISSUE THREAD

**Issue by charlie-quinn** [kayleemenard/kayleemenard#6]
Your scroll-down button disappears (desktop) when the screen's height is scaled down.

**Comment by kayleemenard** [comment]
I only intended for it to exist for medium and large screen sizes. Smaller screen sizes don't have it by default.

**Comment by charlie-quinn** [comment]
Alrighty then! Thanks for the update Kaylee, I can't wait to see it tomorrow!

Sent from my iPhone

On Oct 14, 2015, at 11:18 PM, Kaylee Menard <notifications@github.com<mailto:notifications@github.com>> wrote:

I only intended for it to exist for medium and large screen sizes. Smaller screen sizes don't have it by default.

##
